# The tasks "find_trending_companies" and "research_trending_companies" save their output in JSON type files because:
# 1. They use output_pydantic in the crew.py file and must return JSON that conforms to the schema (BaseModel).
# 2. The system operates in a hierarchical mode (Process.hierarchical)
#    and therefore requires structured output that is easy to pass and interpret between agents.

find_trending_companies:
  description: >
    Find the top trending companies in the news in {sector} by searching the latest news. Find new companies that you've not found before.
  expected_output: >
    A list of trending companies in {sector}
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending companies, provide detailed analysis of each company in a report by searching online
  expected_output: >
    A report containing detailed analysis of each company
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

# the task pick_best_company mentions in the description
# "Send a push notification to the user" - so it should use the tool "push_tool" that we add  
pick_best_company:
  description: >
    Analyze the research findings and pick the best company for investment. 
    Send a push notification to the user with the decision and 1 sentence rationale.
    Then respond with a detailed report on why you chose this company, and which companies were not selected.
  expected_output: >
    The chosen company and why it was chosen; the companies that were not selected and why they were not selected.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
